alert('Брендан Эйх')
alert('JavaScript был создан за 10 дней')
alert('Javascript вскоре появился в Netscape Navigator 2.0 в сентябре 1995 года.')
alert('JavaScript - это не Java')
alert('Спецификация языка JavaScript называется ECMAScript.')